### ISSUE TITLE
Extention's Icon doesnt show on Gome 20.04

### ISSUE THREAD

**Issue by brunnogama** [pemmoura/galaxybuds-gnome-extension#1]
sudo journalctl -xe /usr/bin/gnome-shell | grep buds
[sudo] senha para brunogama: 
ago 14 11:09:09 moody-pc gnome-shell[1873]: [budsBattery] Extension enabled
ago 14 11:09:09 moody-pc gnome-shell[1873]: [budsBattery] Init budsBattIndicator
ago 14 11:09:09 moody-pc gnome-shell[1873]: [budsBattery] Connecting bluetooth controller signals
ago 14 11:09:10 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: moody-pc
ago 14 11:10:01 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: moody-pc
ago 14 11:10:01 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: moody-pc
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
ago 14 11:10:01 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: moody-pc
ago 14 11:10:01 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: moody-pc
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
ago 14 11:10:20 moody-pc gnome-shell[1873]: [budsBattery] Buds inserted event MAC=A8:87:B3:42:62:28
ago 14 11:10:20 moody-pc gnome-shell[1873]: [budsBattery] Gio.IOErrorEnum: Traceback (most recent call last):
                                              File "/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/buds_battery.py", line 11, in <module>
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
ago 14 11:10:21 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: Buds
ago 14 11:10:21 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: Buds
ago 14 11:10:23 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: Galaxy Buds (6228)
ago 14 11:10:23 moody-pc gnome-shell[1873]: [budsBattery] Buds changed event
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:85:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:39:18
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
ago 14 11:10:29 moody-pc gnome-shell[1873]: [budsBattery] Buds inserted event MAC=A8:87:B3:42:62:28
ago 14 11:10:30 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: Galaxy Buds (6228)
ago 14 11:10:30 moody-pc gnome-shell[1873]: [budsBattery] Buds changed event
ago 14 11:10:32 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: Galaxy Buds (6228)
ago 14 11:10:32 moody-pc gnome-shell[1873]: [budsBattery] Buds changed event
ago 14 11:10:33 moody-pc gnome-shell[1873]: [budsBattery] Gio.IOErrorEnum: Traceback (most recent call last):
                                              File "/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/buds_battery.py", line 11, in <module>
ago 14 11:10:33 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: Galaxy Buds (6228)
ago 14 11:10:33 moody-pc gnome-shell[1873]: [budsBattery] Buds changed event
ago 14 11:10:33 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: Galaxy Buds (6228)
ago 14 11:10:33 moody-pc gnome-shell[1873]: [budsBattery] Buds changed event
ago 14 11:10:33 moody-pc gnome-shell[1873]: [budsBattery] Device changed event: Galaxy Buds (6228)
ago 14 11:10:33 moody-pc gnome-shell[1873]: [budsBattery] Buds changed event
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
                                            _connectControllerSignals/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:61:8
                                            enable/<@/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22

**Comment by pemmoura** [comment]
Have you installed bluez and pybluez?

sudo apt install bluez
pip install PyBluez

**Comment by brunnogama** [comment]
It's installed.
When I connect the buds, a% appears quickly in the bar and disappears shortly thereafter.

**Comment by gbaufake** [comment]
same thing here.

**Comment by pemmoura** [comment]
I'm using the galaxy buds plus, and I don't have the original galaxy buds for testing, i'll try to figure what might be wrong when I have the time.

**Comment by pemmoura** [comment]
It would help if someone could provide the rest of the log near the line:

`File "/home/brunogama/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/buds_battery.py", line 11, in `

By running:

`sudo journalctl -xe /usr/bin/gnome-shell `

**Comment by gbaufake** [comment]
```
ago 31 19:29:59 lenovo-x1-carbon-baufaker gnome-shell[14198]: JS ERROR: Exception in callback for signal: device-inserted: TypeError: device.name is null
                                                              _connectControllerSignals/<@/home/gbaufake/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:52:8
                                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                                              enable/<@/home/gbaufake/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
ago 31 19:30:00 lenovo-x1-carbon-baufaker gnome-shell[14198]: JS ERROR: Exception in callback for signal: device-inserted: TypeError: device.name is null
                                                              _connectControllerSignals/<@/home/gbaufake/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:52:8
                                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                                              enable/<@/home/gbaufake/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
ago 31 19:30:00 lenovo-x1-carbon-baufaker gnome-shell[14198]: JS ERROR: Exception in callback for signal: device-inserted: TypeError: device.name is null
                                                              _connectControllerSignals/<@/home/gbaufake/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/extension.js:52:8
                                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                                              enable/<@/home/gbaufake/.local/share/gnome-shell/extensions/galaxy-buds-battery@pemmoura/bluetooth.js:44:22
```

**Comment by brunnogama** [comment]
It is strange because the extension icon appears and disappears shortly thereafter. I’ve already disabled all other extensions to test for conflicts.

Here is the result of the command:






set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad44b65f60), >
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad>
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/bruno>
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource://>
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/bruno>
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad>
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad44c03a70), >
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/bruno>
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource://>
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/bruno>
set 02 10:46:37 moody-pc gnome-shell[106636]: [budsBattery] Device changed even>
set 02 10:46:37 moody-pc gnome-shell[106636]: [budsBattery] Buds changed event
set 02 10:46:37 moody-pc gnome-shell[106636]: [budsBattery] Disable budsBattInd>
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad4519d020), >
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad>
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/bruno>
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource://>
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/bruno>
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad4839da70), >
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad>
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/bruno>
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource://>
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/bruno>
lines 1486-1508/1508 (END)
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad44b65f60), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad41b436c0 ==
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:111 (2dcb7bcdf880 @ 593)
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (1a52168a9970 @ 69)
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:79 (2dcb7bcdf6a0 @ 12)
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad41b436c0 ==
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad44c03a70), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:111 (2dcb7bcdf880 @ 593)
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (1a52168a9970 @ 69)
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:79 (2dcb7bcdf6a0 @ 12)
set 02 10:46:37 moody-pc gnome-shell[106636]: [budsBattery] Device changed event: Galaxy Buds (6228)
set 02 10:46:37 moody-pc gnome-shell[106636]: [budsBattery] Buds changed event
set 02 10:46:37 moody-pc gnome-shell[106636]: [budsBattery] Disable budsBattIndicator
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad4519d020), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad41b436c0 ==
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:111 (2dcb7bcdf880 @ 593)
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (1a52168a9970 @ 69)
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:79 (2dcb7bcdf6a0 @ 12)
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad4839da70), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad41b436c0 ==
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:111 (2dcb7bcdf880 @ 593)
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (1a52168a9970 @ 69)
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:79 (2dcb7bcdf6a0 @ 12)
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1486-1508/1508 (END)
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad44b65f60), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove(>
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad41b436c0 ==
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:111 (2dcb7bcdf880 @ 593)
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (1a52168a9970 @ 69)
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:79 (2dcb7bcdf6a0 @ 12)
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad41b436c0 ==
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad44c03a70), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove(>
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:111 (2dcb7bcdf880 @ 593)
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (1a52168a9970 @ 69)
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:79 (2dcb7bcdf6a0 @ 12)
set 02 10:46:37 moody-pc gnome-shell[106636]: [budsBattery] Device changed event: Galaxy Buds (6228)
set 02 10:46:37 moody-pc gnome-shell[106636]: [budsBattery] Buds changed event
set 02 10:46:37 moody-pc gnome-shell[106636]: [budsBattery] Disable budsBattIndicator
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad4519d020), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove(>
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad41b436c0 ==
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:111 (2dcb7bcdf880 @ 593)
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (1a52168a9970 @ 69)
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:79 (2dcb7bcdf6a0 @ 12)
set 02 10:46:37 moody-pc gnome-shell[106636]: Object St.Icon (0x55ad4839da70), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove(>
set 02 10:46:37 moody-pc gnome-shell[106636]: == Stack trace for context 0x55ad41b436c0 ==
set 02 10:46:37 moody-pc gnome-shell[106636]: #0   55ad42b71368 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:111 (2dcb7bcdf880 @ 593)
set 02 10:46:37 moody-pc gnome-shell[106636]: #1   55ad42b712b8 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (1a52168a9970 @ 69)
set 02 10:46:37 moody-pc gnome-shell[106636]: #2   55ad42b71218 i   /home/brunogama/.local/share/gnome-shell/extensions/panel-indicators@pemmoura/indicators/bluetooth.js:79 (2dcb7bcdf6a0 @ 12)
~

**Comment by pemmoura** [comment]
[2f07c7b](https://github.com/pemmoura/galaxybuds-gnome-extension/commit/2f07c7b2cb144202bca5c724828af1598edcc7b0) should fix the issues, can someone test and let me know?

**Comment by gbaufake** [comment]
@pemmoura Is there a way that I build this extension myself for testing?

**Comment by gbaufake** [comment]
@pemmoura 
Same problem with the new code.
```
set 15 09:49:07 lenovo-p1-baufaker gnome-shell[5221]: [budsBattery] Reset budsBattIndicator
set 15 09:49:07 lenovo-p1-baufaker gnome-shell[5221]: [budsBattery] Extension enabled
set 15 09:49:07 lenovo-p1-baufaker gnome-shell[5221]: [budsBattery] Init budsBattIndicator
set 15 09:49:07 lenovo-p1-baufaker gnome-shell[5221]: [budsBattery] Connecting bluetooth controller signals
set 15 09:49:07 lenovo-p1-baufaker gnome-shell[5221]: [budsBattery] Device changed event: lenovo-p1-baufaker
set 15 09:49:07 lenovo-p1-baufaker gnome-shell[5221]: [budsBattery] Buds inserted event MAC=6C:DD:BC:61:2B:AA
set 15 09:49:07 lenovo-p1-baufaker gnome-shell[5221]: [budsBattery] Enable budsBattIndicator
set 15 09:49:07 lenovo-p1-baufaker gnome-shell[5221]: [budsBattery] Sync budsBattIndicator
set 15 09:49:07 lenovo-p1-baufaker gnome-shell[5221]: [budsBattery] Gio.IOErrorEnum: Operação não permitida
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:49:15 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:50:02 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:50:02 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:50:02 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
set 15 09:50:02 lenovo-p1-baufaker gnome-shell[5221]: Ignoring excess values in shadow definition
```

**Comment by Madeyro** [comment]
Just installed and having this problem as well with Buds Live:

``` shell
$ journalctl -f /usr/bin/gnome-shell | grep budsBattery
dec 21 13:28:22 vulpix gnome-shell[76206]: [budsBattery] Gio.IOErrorEnum: Operation not permitted
```
``` shell
$ rpm -qa *bluez*
bluez-obexd-5.55-1.fc32.x86_64
bluez-5.55-1.fc32.x86_64
bluez-libs-5.55-1.fc32.x86_64
bluez-cups-5.55-1.fc32.x86_64
python3-bluez-0.22-18.fc32.x86_64
$ rpm -qa gnome-shell
gnome-shell-3.36.7-1.fc32.x86_64
```
